// Mocks generated by Mockito 5.4.4 from annotations
// in lietucoach/test/reproduce_regression_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lietucoach/content/content_source.dart' as _i4;
import 'package:lietucoach/packs/pad_pack_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PadPackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPadPackService extends _i1.Mock implements _i2.PadPackService {
  @override
  _i3.Future<_i2.PackStatus> getPackStatus(String? packName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackStatus,
          [packName],
        ),
        returnValue: _i3.Future<_i2.PackStatus>.value(_i2.PackStatus.installed),
        returnValueForMissingStub:
            _i3.Future<_i2.PackStatus>.value(_i2.PackStatus.installed),
      ) as _i3.Future<_i2.PackStatus>);

  @override
  _i3.Future<void> requestDownload(String? packName) => (super.noSuchMethod(
        Invocation.method(
          #requestDownload,
          [packName],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i2.DownloadProgress> downloadProgress(String? packName) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadProgress,
          [packName],
        ),
        returnValue: _i3.Stream<_i2.DownloadProgress>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DownloadProgress>.empty(),
      ) as _i3.Stream<_i2.DownloadProgress>);

  @override
  _i3.Future<String?> getPackPath(String? packName) => (super.noSuchMethod(
        Invocation.method(
          #getPackPath,
          [packName],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> cancelDownload(String? packName) => (super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [packName],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int?> getPackSize(String? packName) => (super.noSuchMethod(
        Invocation.method(
          #getPackSize,
          [packName],
        ),
        returnValue: _i3.Future<int?>.value(),
        returnValueForMissingStub: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);
}

/// A class which mocks [ContentSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentSource extends _i1.Mock implements _i4.ContentSource {
  @override
  String get rootPrefix => (super.noSuchMethod(
        Invocation.getter(#rootPrefix),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#rootPrefix),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#rootPrefix),
        ),
      ) as String);

  @override
  _i3.Future<bool> exists(String? path) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [path],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String> loadString(String? path) => (super.noSuchMethod(
        Invocation.method(
          #loadString,
          [path],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #loadString,
            [path],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #loadString,
            [path],
          ),
        )),
      ) as _i3.Future<String>);
}
