// Mocks generated by Mockito 5.4.4 from annotations
// in lietucoach/test/unit_exam_entry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:lietucoach/content/content_repository.dart' as _i6;
import 'package:lietucoach/content/models.dart' as _i3;
import 'package:lietucoach/packs/packs.dart' as _i7;
import 'package:lietucoach/progress/progress_models.dart' as _i2;
import 'package:lietucoach/progress/progress_store.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:lietucoach/content/content_failure.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserStats_0 extends _i1.SmartFake implements _i2.UserStats {
  _FakeUserStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResult_2<V, F> extends _i1.SmartFake implements _i8.Result<V, F> {
  _FakeResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProgressStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressStore extends _i1.Mock implements _i4.ProgressStore {
  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.LessonProgress?> getLessonProgress(
    String? unitId,
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonProgress, [unitId, lessonId]),
            returnValue: _i5.Future<_i2.LessonProgress?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.LessonProgress?>.value(),
          )
          as _i5.Future<_i2.LessonProgress?>);

  @override
  _i5.Future<List<_i2.LessonProgress>> getUnitLessonProgress(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitLessonProgress, [unitId]),
            returnValue: _i5.Future<List<_i2.LessonProgress>>.value(
              <_i2.LessonProgress>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i2.LessonProgress>>.value(
                  <_i2.LessonProgress>[],
                ),
          )
          as _i5.Future<List<_i2.LessonProgress>>);

  @override
  _i5.Future<List<_i2.LessonProgress>> getAllLessonProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLessonProgress, []),
            returnValue: _i5.Future<List<_i2.LessonProgress>>.value(
              <_i2.LessonProgress>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i2.LessonProgress>>.value(
                  <_i2.LessonProgress>[],
                ),
          )
          as _i5.Future<List<_i2.LessonProgress>>);

  @override
  _i5.Future<void> saveLessonProgress(_i2.LessonProgress? progress) =>
      (super.noSuchMethod(
            Invocation.method(#saveLessonProgress, [progress]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UnitProgress?> getUnitProgress(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitProgress, [unitId]),
            returnValue: _i5.Future<_i2.UnitProgress?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.UnitProgress?>.value(),
          )
          as _i5.Future<_i2.UnitProgress?>);

  @override
  _i5.Future<List<_i2.UnitProgress>> getAllUnitProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUnitProgress, []),
            returnValue: _i5.Future<List<_i2.UnitProgress>>.value(
              <_i2.UnitProgress>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i2.UnitProgress>>.value(
              <_i2.UnitProgress>[],
            ),
          )
          as _i5.Future<List<_i2.UnitProgress>>);

  @override
  _i5.Future<void> saveUnitProgress(_i2.UnitProgress? progress) =>
      (super.noSuchMethod(
            Invocation.method(#saveUnitProgress, [progress]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserStats> getUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, []),
            returnValue: _i5.Future<_i2.UserStats>.value(
              _FakeUserStats_0(this, Invocation.method(#getUserStats, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserStats>.value(
              _FakeUserStats_0(this, Invocation.method(#getUserStats, [])),
            ),
          )
          as _i5.Future<_i2.UserStats>);

  @override
  _i5.Future<void> saveUserStats(_i2.UserStats? stats) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserStats, [stats]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isUnitUnlocked(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#isUnitUnlocked, [unitId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> areAllLessonsCompleted(
    String? unitId,
    List<String>? lessonIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#areAllLessonsCompleted, [unitId, lessonIds]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRepository extends _i1.Mock implements _i6.ContentRepository {
  @override
  _i5.Future<_i8.Result<_i3.Unit, _i8.ContentLoadFailure>> loadUnit(
    String? unitId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadUnit, [unitId]),
            returnValue:
                _i5.Future<_i8.Result<_i3.Unit, _i8.ContentLoadFailure>>.value(
                  _FakeResult_2<_i3.Unit, _i8.ContentLoadFailure>(
                    this,
                    Invocation.method(#loadUnit, [unitId]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i8.Result<_i3.Unit, _i8.ContentLoadFailure>>.value(
                  _FakeResult_2<_i3.Unit, _i8.ContentLoadFailure>(
                    this,
                    Invocation.method(#loadUnit, [unitId]),
                  ),
                ),
          )
          as _i5.Future<_i8.Result<_i3.Unit, _i8.ContentLoadFailure>>);

  @override
  _i5.Future<bool> isUnitAvailable(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#isUnitAvailable, [unitId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> downloadUnit(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadUnit, [unitId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i7.DownloadProgress> downloadProgress(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadProgress, [unitId]),
            returnValue: _i5.Stream<_i7.DownloadProgress>.empty(),
            returnValueForMissingStub: _i5.Stream<_i7.DownloadProgress>.empty(),
          )
          as _i5.Stream<_i7.DownloadProgress>);

  @override
  _i5.Future<_i3.Lesson?> getLesson(String? unitId, String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getLesson, [unitId, lessonId]),
            returnValue: _i5.Future<_i3.Lesson?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.Lesson?>.value(),
          )
          as _i5.Future<_i3.Lesson?>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}
